# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the vertex with minimum key value that is not yet in the MST
#'
#' @param key NumericVector containing the key values of vertices
#' @param mst_set LogicalVector indicating whether vertices are already in the MST
#' @return Index of the vertex with the minimum key value
#' @export
min_key_vertex <- function(key, mst_set) {
    .Call(`_mstPackage_min_key_vertex`, key, mst_set)
}

#'
#' @param n Integer specifying the number of vertices
#' @param num_zeros Nullable integer specifying the number of zero-weight edges to introduce
#' @return NumericMatrix representing the weighted adjacency matrix
#' @export
generate_random_adjacency_matrix <- function(n, num_zeros = NULL) {
    .Call(`_mstPackage_generate_random_adjacency_matrix`, n, num_zeros)
}

#' Find the Minimum Spanning Tree using Prim's algorithm
#'
#' @param adj_matrix Weighted adjacency matrix
#' @return Weighted adjacency matrix of the Minimum Spanning Tree
prim_mst_rcpp <- function(adj_matrix) {
    .Call(`_mstPackage_prim_mst_rcpp`, adj_matrix)
}

#' Find the Minimum Spanning Tree using Kruskal's algorithm
#'
#' @param adj_matrix Weighted adjacency matrix
#' @return Weighted adjacency matrix of the Minimum Spanning Tree
kruskal_mst_rcpp <- function(adj_matrix) {
    .Call(`_mstPackage_kruskal_mst_rcpp`, adj_matrix)
}

#' Convert an adjacency matrix into a list of edges (source, destination, weight)
#'
#' @param adj_matrix Weighted adjacency matrix
#' @return Matrix of edges (source, destination, weight)
adj_matrix_to_edges <- function(adj_matrix) {
    .Call(`_mstPackage_adj_matrix_to_edges`, adj_matrix)
}

